name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x, 22.x ]
    name: Ubuntu NodeJS ${{ matrix.node-version }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Install node modules
        run: yarn install
      - name: Run tests
        run: yarn ci
  build-windows:
    continue-on-error: true
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    name: Windows NodeJS ${{ matrix.node-version }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Install node modules
        run: yarn install
      - name: Run tests
        run: yarn ci
  verify-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    name: Verify README.md
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Install node modules
        run: yarn install
      - name: Verify README.md
        run: npm run readme && git diff --quiet README.md
  verify-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]
    name: Verify NodeJS installation
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Verify install
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false npm install "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/$GITHUB_SHA"
